title: Amen Zwa, Esq.
email: amenzwa@gmail.com
description: 'Publications of <a href="http://amazon.com/author/amenzwa">Amen Zwa, Esq.</a>'
baseurl: ""
url: "https://amenzwa.github.io"
baseurl: ''
paginate: 5
plugins:
  - jekyll-paginate
version: 1.0.0
permalink: pretty
author:
  name: Amen Zwa, Esq.
  url: https://twitter.com/amenzwa
  email: amenzwa@gmail.com